# Generated by Django 5.0.6 on 2024-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('cover', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
